# Generated by Django 2.2.4 on 2019-08-06 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mygarage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('contact_details', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('vehicle_make', models.CharField(max_length=100)),
                ('vehicle_licence', models.CharField(max_length=100)),
                ('vehicle_engine_type', models.CharField(max_length=100)),
                ('customer_comments', models.TextField()),
                ('selected_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
